apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # deployment labels
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
  replicas: 3
    # these are the labels replicaset uses to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      app: nginx
  # this is pod definition
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # here u should change the version, so the pod in replicaset takes the version
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: deployment-demo
    project: roboshop
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80